[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Marc Capell <marc.capell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicli = "0.4"
structopt = "0.2"
itertools = "0.9.0"
regex = "1"
